# Generated by Django 5.2 on 2025-04-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
